#define IDBITMAP_SMILEY 101
#define IDBITMAP_HEIGHTMAP 102

#define IDBITMAP_HEIGHTMAPBACK 103
#define IDBITMAP_GRASS 104
#define IDBITMAP_FUNGUS 105
#define IDBITMAP_ROCK 106
#define IDBITMAP_SAND 107
#define IDBITMAP_PATH 108



